version: '3'

services:
    bank-app:
        container_name: bank-app
        build:
            context: .
            dockerfile: docker/php/8.2/Dockerfile
        image: bank-app
        working_dir: '/var/www'
        volumes:
            - '.:/var/www'
        expose:
            - 9000
        depends_on:
            - bank-db
    bank-nginx:
        container_name: bank-nginx
        build:
            context: ./docker/nginx
        image: bank-nginx
        ports:
            - 8000:80
        volumes:
            - '.:/code'
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - bank-app
    bank-db:
        container_name: bank-db
        image: postgres:14.6
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD

volumes:
    db:
