version: '3'

services:
    bank-app:
        container_name: bank-app
        build:
            context: .
            dockerfile: docker/php/8.1/Dockerfile
        image: bank-app
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        working_dir: '/var/www/html'
        volumes:
            - '.:/var/www/html'
        expose:
            - 9003
        depends_on:
            - bank-db
    bank-nginx:
        container_name: bank-nginx
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - bank-app
    bank-db:
        container_name: bank-db
        image: postgres:14.6
        ports:
            - '${FORWARD_POSTGRES_PORT:-5432}:5432'
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD

volumes:
    db:
